#!/usr/bin/python3

from os import remove as rm
from os.path import exists

alpha_list = list("ABCDEFGHIJKLMNOPQRSTUVWXY")

for letter in alpha_list:
    path = "/tmp/" + letter
    if exists(path):
        rm(path)
if exists("./output.txt"):
    rm("./output.txt")
