#!/usr/bin/python3

from os import remove as rm
from os.path import exists
from glob import glob

alpha_list = list("ABCDEFGHIJKLMNOPQRSTUVWXY")

for letter in alpha_list:
    path = "/tmp/" + letter
    if exists(path):
        rm(path)
outfiles = glob('./*.out')
for file in outfiles:
    rm(file)
